"""Public facade for beta and counterfactual analysis helpers."""

try:
    from .beta_analysis_data import (
        DEFAULT_BENCHMARK_CODE,
        DEFAULT_BETA_LOOKBACK,
        MIN_BETA_OBSERVATIONS,
        AnalysisError,
        BetaEstimator,
        ClosedTrade,
        Lot,
        RunInfo,
        build_closed_trades,
        connect,
        connect_readonly,
        get_run_info,
        last_price,
        load_close_frame,
        load_equity_curve,
        load_fills,
        load_sector_map,
        normalize_date,
        require_tables,
        select_run,
        table_columns,
        trading_days,
    )
    from .beta_analysis_daily import build_daily_beta_decomposition, closed_trades_frame
    from .beta_analysis_metrics import (
        benchmark_close_series,
        cap_sector_weights,
        iter_months,
        month_bounds,
        monthly_metrics,
        overlay_equity_curve,
        parse_positions_json,
        safe_slug,
        sector_return_contribution,
        target_beta_weights,
        write_csv,
    )
except ImportError:  # Direct execution from scripts/.
    from beta_analysis_data import (
        DEFAULT_BENCHMARK_CODE,
        DEFAULT_BETA_LOOKBACK,
        MIN_BETA_OBSERVATIONS,
        AnalysisError,
        BetaEstimator,
        ClosedTrade,
        Lot,
        RunInfo,
        build_closed_trades,
        connect,
        connect_readonly,
        get_run_info,
        last_price,
        load_close_frame,
        load_equity_curve,
        load_fills,
        load_sector_map,
        normalize_date,
        require_tables,
        select_run,
        table_columns,
        trading_days,
    )
    from beta_analysis_daily import build_daily_beta_decomposition, closed_trades_frame
    from beta_analysis_metrics import (
        benchmark_close_series,
        cap_sector_weights,
        iter_months,
        month_bounds,
        monthly_metrics,
        overlay_equity_curve,
        parse_positions_json,
        safe_slug,
        sector_return_contribution,
        target_beta_weights,
        write_csv,
    )

__all__ = [
    "DEFAULT_BENCHMARK_CODE",
    "DEFAULT_BETA_LOOKBACK",
    "MIN_BETA_OBSERVATIONS",
    "AnalysisError",
    "BetaEstimator",
    "ClosedTrade",
    "Lot",
    "RunInfo",
    "benchmark_close_series",
    "build_closed_trades",
    "build_daily_beta_decomposition",
    "cap_sector_weights",
    "closed_trades_frame",
    "connect",
    "connect_readonly",
    "get_run_info",
    "iter_months",
    "last_price",
    "load_close_frame",
    "load_equity_curve",
    "load_fills",
    "load_sector_map",
    "month_bounds",
    "monthly_metrics",
    "normalize_date",
    "overlay_equity_curve",
    "parse_positions_json",
    "require_tables",
    "safe_slug",
    "sector_return_contribution",
    "select_run",
    "table_columns",
    "target_beta_weights",
    "trading_days",
    "write_csv",
]
